backend:
  name: github
  repo: tip-aaron/portfolio  # <-- change this
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: oauth
  allowed_users:
    - tip-aaron
    - Ragudos

media_folder: "public/uploads"      # where uploaded files go
public_folder: "/uploads"           # served URL

collections:
  # BLOG POSTS
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "publishedOn", label: "Published On", widget: "datetime" }
      - { name: "updatedOn", label: "Updated On", widget: "datetime", required: false }
      - { name: "draft", label: "Draft", widget: "boolean", required: false }
      - { name: "body", label: "Content", widget: "markdown" }

  # CERTIFICATIONS
  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "External Link", widget: "string" }
      - { name: "publishedOn", label: "Published On", widget: "datetime" }
      - { name: "updatedOn", label: "Updated On", widget: "datetime", required: false }
      - { name: "draft", label: "Draft", widget: "boolean", required: false }

  # PROJECTS
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "Project Link", widget: "string" }
      - { name: "publishedOn", label: "Published On", widget: "datetime" }
      - { name: "updatedOn", label: "Updated On", widget: "datetime", required: false }
      - { name: "draft", label: "Draft", widget: "boolean", required: false }
